version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "185137893827"
    AWS_DEFAULT_REGION: "ap-south-1"
    ECR_REPOSITORY_NAME: "javatechie-registry"
    ECS_CONTAINER_NAME: "javatechie-registry"

phases:
  pre_build:
    commands:
      - echo "===== PRE-BUILD START ====="
      - mvn clean install -DskipTests
      - mv target/*.jar target/app.jar
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo "===== BUILD START ====="
      - ls -l target
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "===== POST-BUILD START ====="
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - |
        printf '[{"name":"%s","imageUri":"%s"}]' $ECS_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json